Tux Racer 0.60.1
Added web files for inclusion in dist-tarball, hack to work around compile problems with old gl.h files, check for glext.h and others

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -725,7 +725,7 @@ fi
 
 PACKAGE=tuxracer
 
-VERSION="0.60"
+VERSION="0.60.1"
 
 if test "`cd $srcdir && pwd`" != "`pwd`" && test -f $srcdir/config.status; then
   { echo "configure: error: source directory already configured; run "make distclean" there first" 1>&2; exit 1; }
@@ -3647,10 +3647,62 @@ else
 fi
 done
 
+for ac_hdr in "GL/glext.h" 
+do
+ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
+echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&6
+echo "configure:3655: checking for $ac_hdr" >&5
+if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  cat > conftest.$ac_ext <<EOF
+#line 3660 "configure"
+#include "confdefs.h"
+#include <$ac_hdr>
+EOF
+ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
+{ (eval echo configure:3665: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
+if test -z "$ac_err"; then
+  rm -rf conftest*
+  eval "ac_cv_header_$ac_safe=yes"
+else
+  echo "$ac_err" >&5
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  eval "ac_cv_header_$ac_safe=no"
+fi
+rm -f conftest*
+fi
+if eval "test \"`echo '$ac_cv_header_'$ac_safe`\" = yes"; then
+  echo "$ac_t""yes" 1>&6
+    ac_tr_hdr=HAVE_`echo $ac_hdr | sed 'y%abcdefghijklmnopqrstuvwxyz./-%ABCDEFGHIJKLMNOPQRSTUVWXYZ___%'`
+  cat >> confdefs.h <<EOF
+#define $ac_tr_hdr 1
+EOF
+ 
+else
+  echo "$ac_t""no" 1>&6
+fi
+done
+
 CFLAGS="$ac_save_CFLAGS" 
 
+if test "x$ac_cv_header_GL_glext_h" = "xno" ; then
+   echo
+   echo "*****************************************************************"
+   echo "ERROR: You are missing the file glext.h."
+   echo "You can get a copy at"
+   echo "http://oss.sgi.com/projects/ogl-sample/ABI/glext.h"
+   echo "Place it in the directory /usr/include/GL."
+   echo "*****************************************************************"
+   echo
+   exit 1
+fi
+
 echo $ac_n "checking for glutKeyboardUpFunc in -lglut""... $ac_c" 1>&6
-echo "configure:3654: checking for glutKeyboardUpFunc in -lglut" >&5
+echo "configure:3706: checking for glutKeyboardUpFunc in -lglut" >&5
 ac_lib_var=`echo glut'_'glutKeyboardUpFunc | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -3658,7 +3710,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lglut  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 3662 "configure"
+#line 3714 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -3669,7 +3721,7 @@ int main() {
 glutKeyboardUpFunc()
 ; return 0; }
 EOF
-if { (eval echo configure:3673: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:3725: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -3698,7 +3750,7 @@ fi
 
 if test "x$ac_cv_lib_glut_glutKeyboardUpFunc" = "xno" ; then
                         echo $ac_n "checking for main in -lglut32""... $ac_c" 1>&6
-echo "configure:3702: checking for main in -lglut32" >&5
+echo "configure:3754: checking for main in -lglut32" >&5
 ac_lib_var=`echo glut32'_'main | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -3706,14 +3758,14 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lglut32  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 3710 "configure"
+#line 3762 "configure"
 #include "confdefs.h"
 
 int main() {
 main()
 ; return 0; }
 EOF
-if { (eval echo configure:3717: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:3769: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -1,6 +1,6 @@
 dnl Process this file with autoconf to produce a configure script.
 AC_INIT(src/tuxracer.h)
-AM_INIT_AUTOMAKE(tuxracer, "0.60")
+AM_INIT_AUTOMAKE(tuxracer, "0.60.1")
 AM_CONFIG_HEADER(config.h)
 
 dnl Check system type
@@ -146,14 +146,28 @@ if test "x$ac_cv_lib_GLU_gluLookAt" = "xno" ; then
     fi
 fi
 
-dnl check for glx.h
+dnl check for glx.h, glext.h
 dnl Set CFLAGS before this check so that it will be found if in
 dnl non-standard location -- thanks to Kevin Moule <krmoule@cgl.uwaterloo.ca>
 dnl for suggestion 
 ac_save_CFLAGS="$CFLAGS"
 CFLAGS="$TUXRACER_EXTRA_COMPILEFLAGS $CFLAGS"
 AC_CHECK_HEADERS( "GL/glx.h" )
+AC_CHECK_HEADERS( "GL/glext.h" )
 CFLAGS="$ac_save_CFLAGS" 
+
+dnl Must have glext.h to compile
+if test "x$ac_cv_header_GL_glext_h" = "xno" ; then
+   echo
+   echo "*****************************************************************"
+   echo "ERROR: You are missing the file glext.h."
+   echo "You can get a copy at"
+   echo "http://oss.sgi.com/projects/ogl-sample/ABI/glext.h"
+   echo "Place it in the directory /usr/include/GL."
+   echo "*****************************************************************"
+   echo
+   exit 1
+fi
 
 dnl Check for glut
 AC_CHECK_LIB(glut, glutKeyboardUpFunc)
